# Generated by Django 4.1.2 on 2023-04-05 16:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_materia_estadoanimoantes_materia_estadoanimodespues_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materia',
            old_name='horario',
            new_name='horarioI',
        ),
        migrations.AddField(
            model_name='materia',
            name='horarioF',
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
    ]
