# Generated by Django 4.0 on 2023-05-03 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_notas_nota'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Estudiante',
        ),
    ]
