# Generated by Django 4.0 on 2023-05-07 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_carrera'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia',
            name='estadoAnimoAntes',
        ),
        migrations.RemoveField(
            model_name='materia',
            name='estadoAnimoDespues',
        ),
    ]
