# Generated by Django 4.0 on 2023-05-07 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_materia_estadoanimoantes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoAnimoAntes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estadoAnimoAntes', models.IntegerField(choices=[(1, 'FELIZ 😃'), (2, 'TRISTE 😭'), (3, 'ESTRESADO 😵\u200d💫'), (4, 'ABURRIDO 😐')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoAnimoDespues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estadoAnimoDespues', models.IntegerField(choices=[(1, 'FELIZ 😃'), (2, 'TRISTE 😭'), (3, 'ESTRESADO 😵\u200d💫'), (4, 'ABURRIDO 😐')], default=1)),
            ],
        ),
    ]
