# Generated by Django 4.0 on 2023-05-07 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_estadoanimoantes_estadoanimodespues'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EstadoAnimoAntes',
        ),
        migrations.DeleteModel(
            name='EstadoAnimoDespues',
        ),
    ]
