# Generated by Django 4.0 on 2023-05-07 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('app', '0017_delete_estadoanimoantes_delete_estadoanimodespues'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoAnimoDespues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estadoAnimoDespues', models.IntegerField(choices=[(1, 'FELIZ 😃'), (2, 'TRISTE 😭'), (3, 'ESTRESADO 😵\u200d💫'), (4, 'ABURRIDO 😐')], default=1)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.materia')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='EstadoAnimoAntes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estadoAnimoAntes', models.IntegerField(choices=[(1, 'FELIZ 😃'), (2, 'TRISTE 😭'), (3, 'ESTRESADO 😵\u200d💫'), (4, 'ABURRIDO 😐')], default=1)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.materia')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
